[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/declantsien/surfman-chains.git"]
git = "https://github.com/declantsien/surfman-chains.git"
rev = "df8d9ed04f516873f8e6ad7446a233238d783694"
replace-with = "vendored-sources"

[source."https://github.com/declantsien/surfman.git"]
git = "https://github.com/declantsien/surfman.git"
rev = "682fc7f787432de7b289e4caf4d8e248f85268c9"
replace-with = "vendored-sources"

[source."https://github.com/declantsien/webrender_surfman.git"]
git = "https://github.com/declantsien/webrender_surfman.git"
rev = "6d5c67923d85f12d3bf0f5e4fbee159772d49572"
replace-with = "vendored-sources"

[source."https://github.com/declantsien/winit"]
git = "https://github.com/declantsien/winit"
rev = "d80de2ea150a36d078bd19b6c6ce1cc299304fc5"
replace-with = "vendored-sources"

[source."https://github.com/servo/webrender.git"]
git = "https://github.com/servo/webrender.git"
rev = "da3fba3c4751c0bf4098309ecb4329110b062146"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
